# Generated by Django 2.2.12 on 2020-04-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile_no',
            field=models.IntegerField(verbose_name=15),
        ),
    ]
