# Generated by Django 2.2.12 on 2020-04-26 14:59

from django.db import migrations, models

import main.core


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_auto_20200426_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile_no',
            field=models.CharField(default='1234567890', max_length=12, validators=[main.core.validate_digit_length],
                                   verbose_name='Phone number'),
        ),
    ]
