# Generated by Django 2.2.12 on 2020-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_auto_20200426_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
