# Generated by Django 2.2.12 on 2020-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_auto_20200430_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
