# Generated by Django 2.2.12 on 2020-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_auto_20200430_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('property', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
