# Generated by Django 2.2.12 on 2020-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVendorAssign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=200)),
                ('client_project_id', models.CharField(max_length=200)),
                ('vendor_id', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=15)),
                ('links', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
