# Generated by Django 2.2.12 on 2020-05-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200502_1909'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectvendorassign',
            table='project_vendor_assign',
        ),
    ]
