# Generated by Django 2.2.12 on 2020-05-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200502_1929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectvendorassign',
            table='app_project_vendor_assign',
        ),
    ]
