# Generated by Django 2.2.12 on 2020-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200502_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVendorUserAssign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=200)),
                ('client_project_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('none', 'None'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('quota_full', 'Quota Full')], default=('none', 'None'), max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_project_vendor_user_assign',
            },
        ),
    ]
