# Generated by Django 2.2.12 on 2020-05-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_projectvendoruserassign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectvendoruserassign',
            unique_together={('vendor_id', 'project_id', 'ip_address')},
        ),
    ]
