# Generated by Django 2.2.12 on 2020-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200503_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvendoruserassign',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('quota_full', 'Quota Full')], default='none', max_length=255),
        ),
    ]
